### ISSUE TITLE
Hey pretrained weights are overfitted.

### ISSUE THREAD

**Issue by karandeepdps** [penny4860/YOLO-detector#23]
Can you please confirm as i am getting large number of bound boxes for example images which you have provided.
I am not finetuning just using your weights.

**Comment by penny4860** [comment]
@karandeepdps 

I tried to reproduce the results, but there was no problem you mentioned. Please follow the link below.
: https://github.com/penny4860/Yolo-digit-detector/blob/master/detection_example.ipynb

**Comment by karandeepdps** [comment]
Hey can i get your final weights which u have trained on svhn complete dataset.

**Comment by penny4860** [comment]
As I said, follow https://github.com/penny4860/Yolo-digit-detector/blob/master/detection_example.ipynb.
The document specifies the weight file path.
