### ISSUE TITLE
pre-train model

### ISSUE THREAD

**Issue by hsl20130659** [penny4860/YOLO-detector#24]
why the pre-train model has a bad results, the digits are not detect

**Comment by penny4860** [comment]
Thank you for using the project. However, after checking, [the pretrained weight file](https://drive.google.com/drive/folders/1Lg3eAPC39G9GwVTCH3XzF73Eok-N-dER) works well.
Does the ipython notebook script at https://github.com/penny4860/Yolo-digit-detector/blob/master/detection_example.ipynb not run properly using a weight file? Download the weight file from the above path and load it when you run ipython notebook

**Comment by hsl20130659** [comment]
I have known the reason, the code need the keras version you assigned. I reinstall the keras ,and it does work ,but the result is not good on my test pictures

**Comment by penny4860** [comment]
Something's wrong. As a result of the notebook file, two boxes in the sample image must be recognized.

**Comment by hsl20130659** [comment]
I give you some photos to test , and you show me the result on the 


- 

> Something's wrong. As a result of the notebook file, two boxes in the sample image must be recognized.

I give you some photos to test , and you show me the result on the pictures.but I dont know how to give you pictures

**Comment by LIZHAONAN** [comment]
Thanks for sharing this project! I also ran into this problem that pre-trained model gave bad results. Could you please have another look at the pre-trained model and the code? I'm using Python3.5 on my MacBook. Any help will be appreciated!

**Comment by lzn87** [comment]
> I give you some photos to test , and you show me the result on the
> 
> 
> > Something's wrong. As a result of the notebook file, two boxes in the sample image must be recognized.
> 
> I give you some photos to test , and you show me the result on the pictures.but I dont know how to give you pictures

Hi, I also ran into this problem and resolved it by downgrading my tf and keras versions. Please double check with yours. I hope this will help!

**Comment by penny4860** [comment]
@LIZHAONAN Thank you for your comment! Required package is specified in https://github.com/penny4860/Yolo-digit-detector#0-requirement
