### ISSUE TITLE
SVHN labeling dataset

### ISSUE THREAD

**Issue by Lepiloff** [penny4860/YOLO-detector#25]
@penny4860 hi! Do you have SVHN dataset with labels for YOLO?

**Comment by penny4860** [comment]
Yes, you can refer https://github.com/penny4860/Yolo-digit-detector#3-svhn-dataset-in-pascal-voc-annotation-format

**Comment by Lepiloff** [comment]
@penny4860 Thank you so much!

**Comment by Lepiloff** [comment]
@penny4860 
I found that the numbers 1,2,3,4,5,6,7,8,9,10 are used in the   https://github.com/penny4860/svhn-voc-annotation-format/tree/master/annotation and there is no digit 0. How then is the  0 detected?

**Comment by penny4860** [comment]
Label 10 means the number 0.
