### ISSUE TITLE
Extraneous detection boxes on sample input using pre-trained weight file

### ISSUE THREAD

**Issue by DamirWallener** [penny4860/YOLO-detector#27]
See attached images. It looks like the "actual" digits are being picked up correctly, but the results are getting clouded by a large number of '1.00' boxes. The two images reported:

> 18-boxes are detected
> 26-boxes are detected

That was with the threshold pushed all the way up to 0.99999. With the threshold at the original 0.3, the number of boxes is 64 and 87.
<img width="586" alt="Screen Shot 2019-05-09 at 12 56 58 PM" src="https://user-images.githubusercontent.com/12688219/57482850-8a095000-725a-11e9-8a4d-53175bdaa412.png">
<img width="588" alt="Screen Shot 2019-05-09 at 12 57 12 PM" src="https://user-images.githubusercontent.com/12688219/57482851-8a095000-725a-11e9-9f33-1d0ce94df7bc.png">

**Comment by gardethk** [comment]
Same problem here, i don't know what is causing this problem. I also tested it with another set of pictures with numbers, same result with the pre-trained weight file.

**Comment by penny4860** [comment]
The above phenomenon can not be reproduced in my execution environment. Please check keras version and tensorflow version.

**Comment by elfaizamine** [comment]
same issue here

**Comment by Amit12690** [comment]
I got the same issue , but when I installed the tensorflow , keras versions as mentioned in the readme , it worked perfectly. Looks like heavily dependent on the older version of tensorflow

**Comment by DamirWallener** [comment]
If there is that heavy a version dependency, that is highly problematic. It
suggests the model isn't doing what we think it's doing.

**Comment by Amit12690** [comment]
With a bit of testing , I found that , it may only be dependent on the Keras version.  
Gave extraneous boxes with keras 2.2.4
But worked perfectly after downgrading to keras 2.1.1 as indicated by the author irrespective of TensorFlow version  (tried tf-1.12 )

**Comment by penny4860** [comment]
@Amit12690 thank you for testing

**Comment by manyaafonso** [comment]
I get the same problem even with the versions of tensorflow and keras being used by the author of the software. Any suggestion, @penny4860 ? I am using ubuntu, and i notice that you used windows. Could there be some dependency I am missing?

**Comment by esysss** [comment]
same issue here.
