### ISSUE TITLE
Did you train your model from scrath without load any pretrained weight?

### ISSUE THREAD

**Issue by bowlderstudio** [penny4860/YOLO-detector#32]
Did you train your model from scrath without load pretrained weight of yolo on coco dataset or some other pretrained version of yolo?

**Comment by penny4860** [comment]
I loaded resnet50's imagenet weight and started training.

**Comment by bowlderstudio** [comment]
From the config file, I can see that you have 20 epoch for the first training phase, and 100 epoch for the second training phase. Is that what you total trained epoch for your real problem?

**Comment by penny4860** [comment]
The yolo v2 used in this project is an early model in the deep learning period, and it is difficult to train. So it needs some elaborate tuning and some tricks. In the case of me, I trained the way it is listed at [2-training-from-scratch](https://github.com/penny4860/Yolo-digit-detector#2-training-from-scratch)

In the case of [retinanet](https://github.com/penny4860/retinanet-digit-detector) or [yolo v3](https://github.com/penny4860/tf2-eager-yolo3#2-training-from-scratch) that came out after that, learning was done well without such tricks.
