### ISSUE TITLE
Yolo weights file

### ISSUE THREAD

**Issue by ivder** [penny4860/YOLO-detector#33]
Hi do you have the trained weights file that I can use directly on original darknet? Training from scratch could be time consuming

**Comment by penny4860** [comment]
No no. This project only provides keras weight files.

**Comment by manyaafonso** [comment]
@penny4860 you wou;d gain a lot more users and citations if you were to provide the weights ttrained over the entire SVHN dataset. Think about it.

**Comment by penny4860** [comment]
@manyaafonso Thank you for your comment. The digit detector trained by the svhn full dataset is provided by s provided by another project that I have implemented.

* yolov3 : https://github.com/penny4860/tf2-eager-yolo3#2-svhn-dataset--httpufldlstanfordeduhousenumbers
* retinanet : https://github.com/penny4860/retinanet-digit-detector
