### ISSUE TITLE
input size

### ISSUE THREAD

**Issue by esysss** [penny4860/YOLO-detector#36]
what is input_size and anchors in from_scrach.JSON and from_scrach2.JSON ?

**Comment by AIWintermuteAI** [comment]
input_size is the size of input image :)
for anchors, have a look at my video explaining it very simple here https://youtu.be/87c6dCgXeJo or read in original Github repository for darknet YOLO https://github.com/pjreddie/darknet/issues/568
if your question was answered, please close the issue

**Comment by esysss** [comment]
Thanks for the links for anchor
about the input size when you say : 
"input_size":           416,
Does it mean the size of our training images is 416 pixels?
and what happens if the training input be bigger or smaller?

**Comment by AIWintermuteAI** [comment]
Well, the script will resize all the images in your dataset to the input_size for you before feeding them to network.. If the size of images in your dataset is much smaller or bigger(e.g. 32x32 or 4000x3000)the result will be suboptimal.
The network input is fixed, so if the image is NOT resized, then it will just throw an error.

**Comment by esysss** [comment]
I understood
thanks
