### ISSUE TITLE
Is your notebook directly use weight.h5 from google?

### ISSUE THREAD

**Issue by kylehh** [penny4860/YOLO-detector#38]
Hi Penny

Nice work on digital recognition
I tried your notebook with weight download from google drive
but the prediction shows 50+ boxes detection
Even set threshold to be 0.99, still have 30+ boxes detected

Any hints on repeating your notebook result?

**Comment by LevavasseurYann** [comment]
Already resolved here: https://github.com/penny4860/Yolo-digit-detector/issues/27
